# Generated by Django 4.1.2 on 2022-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('rut', models.TextField(max_length=13, unique=True)),
                ('correo', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=50)),
                ('contraseña1', models.TextField(max_length=50)),
                ('contraseña2', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=50, unique=True)),
                ('nombre', models.TextField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=50, unique=True)),
                ('nombre', models.TextField(max_length=50)),
                ('tipo', models.TextField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_bd/')),
            ],
        ),
    ]
